version: '3'

services:
  db:
    image: mysql:5.7
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "8500:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    deploy:
      placement:
        constraints: [node.role == manager]
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    networks:
      - serverdb
      - admindb
      - grafanadb
      - authdb

  auth:
    image: anamariamicu/cc-cinema-proiect-auth
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - '8004:8004'
    depends_on:
      - db
    networks:
      - serverauth
      - authdb
      - adminauth

  admin:
    image: anamariamicu/cc-cinema-proiect-admin
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - '8000:8000'
    depends_on:
      - db
      - auth
    networks:
      - admininterface
      - admindb
      - adminauth
      
  admin-interface:
    image: anamariamicu/cc-cinema-proiect-admin-interface
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - '8001:8001'
    depends_on:
      - admin-interface
      - db
    networks:
      - admininterface
    stdin_open: true
    tty: true

  server:
    image: anamariamicu/cc-cinema-proiect-server
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - '8002:8002'
    depends_on:
      - db
      - auth
    networks:
      - serverdb
      - serverclient
      - serverauth

  client:
    image: anamariamicu/cc-cinema-proiect-client
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - '8003:8003'
    depends_on:
      - server
      - db
    networks:
      - serverclient
    stdin_open: true
    tty: true

  grafana:
    image: grafana/grafana:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - '3000:3000'
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=adminpass
    user: "0"
    depends_on:
      - db
    networks:
      - grafanadb

networks:
  serverdb:
  serverclient:
  admininterface:
  admindb:
  grafanadb:
  authdb:
  serverauth:
  adminauth:
