version: '3.1'

services:
  db:
    image: mysql:5.7
    ports:
      - "8500:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d/:ro
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    networks:
      - serverdb
      - admindb
      - grafanadb
      - authdb
    stdin_open: true
    tty: true

  auth:
    build: ./auth
    links:
      - db:mysql
    ports:
      - '8004:8004'
    depends_on:
      - db
    networks:
      - adminauth
      - serverauth
      - authdb
    stdin_open: true
    tty: true

  admin:
    build: ./admin
    links:
      - db:mysql
    ports:
      - '8000:8000'
    depends_on:
      - db
    networks:
      - admininterface
      - admindb
      - adminauth
      - konggateway
    stdin_open: true
    tty: true
      
  admin-interface:
    build: ./admin-interface
    ports:
      - '8001:8001'
    links:
      - db
      - admin
    depends_on:
      - db
      - admin
    networks:
      - admininterface
    stdin_open: true
    tty: true

  client:
    build: ./client
    ports:
      - '8003:8003'
    links:
      - db
      - server
    depends_on:
      - db
      - server
    networks:
      - serverclient
    stdin_open: true
    tty: true

  server:
    build: ./server
    links:
      - db:mysql
      - auth
    ports:
      - '8002:8002'
    depends_on:
      - db
      - auth
    networks:
      - serverdb
      - serverclient
      - serverauth
      - konggateway
    stdin_open: true
    tty: true

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - ./grafana:/var/lib/grafana
    user: "0"
    links:
      - db
    depends_on:
      - db
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=adminpass
    networks:
      - grafanadb

  kong:
    image: kong:latest
    volumes:
      - ./kong:/usr/local/kong/declarative
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - 80:8000
      - 443:8443
    networks:
      - konggateway

networks:
  serverdb:
  serverclient:
  admininterface:
  admindb:
  grafanadb:
  authdb:
  adminauth:
  serverauth:
  konggateway:
