version: '3'

services:
  db:
    image: mysql:5.7
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "8500:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    deploy:
      placement:
        constraints: [node.role == manager]
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    networks:
      - serverdb
      - admindb
      - authdb
      - adminerdb

  auth:
    image: anamariamicu/cc-cinema-proiect-auth
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - '8004:8004'
    depends_on:
      - db
    networks:
      - serverauth
      - authdb
      - adminauth
      - konggateway

  admin:
    image: anamariamicu/cc-cinema-proiect-admin
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - '8000:8000'
    depends_on:
      - db
      - auth
    networks:
      - admindb
      - adminauth
      - konggateway
    environment:
      URL_AUTH: "http://auth:8004"
      
  interface:
    image: anamariamicu/cc-cinema-proiect-interface
    deploy:
      placement:
        constraints: [node.role == manager]
    ports:
      - '8005:8005'
    depends_on:
      - kong
    networks:
      - konggateway
    environment:
      URL_GATEWAY: "http://kong:8000"
    stdin_open: true
    tty: true

  server:
    image: anamariamicu/cc-cinema-proiect-server
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - '8002:8002'
    depends_on:
      - db
      - auth
    networks:
      - serverdb
      - serverauth
      - konggateway
    environment:
      URL_AUTH: "http://auth:8004"

  kong:
    image: kong:latest
    volumes:
      - ./kong:/usr/local/kong/declarative
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - 80:8000
      - 443:8443
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - konggateway

  adminer:
    image: adminer
    ports:
      - '8080:8080'
    networks:
      - adminerdb
    depends_on:
      - db

networks:
  serverdb:
  admindb:
  authdb:
  serverauth:
  adminauth:
  konggateway:
  adminerdb:
